[workspace]
resolver = "2"
members = [
    "proto-packet-parse",
    "proto-packet-tree",
]

[workspace.dependencies]
proto-packet-tree = { path = "proto-packet-tree" } # todo -- path dependency

custom-string = "0.7.0-rc.1"
lex = "0.13.0-rc.1"
